### ISSUE TITLE
Add views for step and wizard

### ISSUE THREAD

**Issue by nesnoj** [stadt-land-energie-projekt/sl-app#102]
Currently there are no steps, hit it!

Create views for app flow:
![image](https://github.com/stadt-land-energie-projekt/sl-app/assets/15910173/5402489b-beef-46a7-9353-d129b73f7825)

Like the wizard from [EPP app](https://epp.rl-institut.de/de/) but use views instead of doing it the JS way

**Comment by josihoppe** [comment]
@nesnoj RIght now there are the following views: home, map, details, parameters, results, robustness
I am a little bit confused, because the current order of results/robustness is different then in the app flow and also the page for robustness seems to me like its doing something different right now. Could you check if the results and robustness pages are doing what they are supposed to be doing or if they need to be changed or even new pages added to gain the structure of the app flow?

**Comment by josihoppe** [comment]
@nesnoj I had a question about the placement of the buttons.
Should they be on top in the header as previous/next Buttons on the sides of the vizwar (version 1 in picture)
Or should there be next-Buttons on the page itself, placed underneath the content where the user is supposed to interact? (version 2)

![Bildschirmfoto zu 2024-08-20 11-10-47](https://github.com/user-attachments/assets/80aa6cab-430b-4929-9763-896886840f5b)

**Comment by josihoppe** [comment]
> Thx @josihoppe for working on this!
> 
> Good point. I prefer version 1 as the left panel might gets too packed in some steps. Also, the layout may change in later steps (no left panel).

That change will be merged with #123
